### ISSUE TITLE
🤔 Start thinking about project ideas & the technical stack

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v32-bears-team-08#2]
**__Task Description__**
- [ ] Check out apps that Voyage teams have created in prior Voyage by reviewing the [Project Showcase](https://medium.com/chingu/chingu-fall-project-showcase-c6bf0f8210ab)
- [ ] Come up with 1 to 3 ideas for projects you'd like to build so you can discuss them with the rest of the team when the Voyage starts. Record your ideas in the [Project Ideas Spreadsheet](https://drive.google.com/file/d/1ZTZczWICPglpRJ1gchw9giYNs2jfnvfQ/view?usp=sharing).
- [ ] Think about what technical stack you'd like to use to build that app. You can add your technical interest and background in the [Team Directory](https://drive.google.com/file/d/13AUbBu1H8Y2CDCUcnipeLk7hR7hcbUH2/view?usp=sharing). Similarly, you'll discuss this as a team at the start of the Voyage. 

**__Technical Considerations__**
N/a

**__Additional Considerations__**
N/a
